# Generated by Django 4.2 on 2026-02-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light Exercise'), ('moderate', 'Moderate Exercise'), ('active', 'Very Active')], max_length=20, null=True)),
                ('health_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_preference', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto')], max_length=20, null=True)),
                ('goal', models.CharField(choices=[('loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain', 'Muscle Gain')], default='maintain', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
