# Generated by Django 6.0.2 on 2026-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of food allergies (e.g., peanuts, shellfish, dairy)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart Disease'), ('none', 'None')], default='none', help_text='Select primary medical condition for dietary recommendations', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sodium_limit_mg',
            field=models.IntegerField(default=2300, help_text='Daily sodium limit in mg (default: 2300 for adults)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sugar_limit_g',
            field=models.IntegerField(default=50, help_text='Daily added sugar limit in grams (default: 50g)'),
        ),
    ]
