# Generated by Django 6.0.2 on 2026-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_habittrack_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart Disease'), ('obesity', 'Obesity'), ('none', 'None')], default='none', help_text='Select primary medical condition for dietary recommendations', max_length=100),
        ),
    ]
