# Generated by Django 6.0.2 on 2026-03-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_medical_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_sample_reports(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        HealthReport = apps.get_model('accounts', 'HealthReport')
        UserProfile = apps.get_model('accounts', 'UserProfile')

        samples = [
            {'username': 'krishna_sai', 'first_name': 'Krishna', 'last_name': 'Sai', 'weight': 70.0, 'health_condition': 'None', 'goal': 'maintain', 'goal_achieved': False},
            {'username': 'venkat', 'first_name': 'Venkat', 'last_name': '', 'weight': 82.5, 'health_condition': 'Hypertension', 'goal': 'loss', 'goal_achieved': True},
            {'username': 'sample_user', 'first_name': 'Demo', 'last_name': 'User', 'weight': 65.0, 'health_condition': 'Diabetes', 'goal': 'gain', 'goal_achieved': False},
        ]
        for entry in samples:
            user, created = User.objects.get_or_create(
                username=entry['username'],
                defaults={
                    'first_name': entry['first_name'],
                    'last_name': entry['last_name'],
                    'email': f"{entry['username']}@example.com",
                }
            )
            # ensure profile exists
            UserProfile.objects.get_or_create(user=user)
            HealthReport.objects.get_or_create(
                user=user,
                weight=entry['weight'],
                health_condition=entry['health_condition'],
                goal=entry['goal'],
                goal_achieved=entry['goal_achieved'],
            )

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('health_condition', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain', 'Muscle Gain')], default='maintain', max_length=20)),
                ('goal_achieved', models.BooleanField(default=False, help_text='Has the user achieved their goal?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Report',
                'verbose_name_plural': 'Health Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_sample_reports),
    ]
