# Generated by Django 6.0.2 on 2026-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_healthreport'),
    ]

    def populate_final_weights(apps, schema_editor):
        HealthReport = apps.get_model('accounts', 'HealthReport')
        # set example final weights for our demo users
        HealthReport.objects.filter(user__username='venkat').update(final_weight=75.0)
        HealthReport.objects.filter(user__username='krishna_sai').update(final_weight=65.0)
        # sample_user remains null to represent in-progress

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='final_weight',
            field=models.FloatField(blank=True, help_text='Weight after following diet plan (if available)', null=True),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='weight',
            field=models.FloatField(help_text='Starting weight in kg'),
        ),
        migrations.RunPython(populate_final_weights),
    ]
