# Generated by Django 6.0.2 on 2026-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_healthreport_final_weight_alter_healthreport_weight'),
    ]

    def set_sample_diet_plans(apps, schema_editor):
        HealthReport = apps.get_model('accounts', 'HealthReport')
        # Set sample diet plans based on user
        HealthReport.objects.filter(user__username='krishna_sai').update(assigned_diet_plan='Vegetarian Balanced')
        HealthReport.objects.filter(user__username='venkat').update(assigned_diet_plan='Low Sodium')
        HealthReport.objects.filter(user__username='sample_user').update(assigned_diet_plan='Diabetic Friendly')

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='assigned_diet_plan',
            field=models.CharField(default='Standard', help_text='Assigned diet plan name', max_length=50),
        ),
        migrations.RunPython(set_sample_diet_plans),
    ]
