# Generated by Django 6.0.2 on 2026-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_ingredient_grocerylist_foodingredient_useringredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0, help_text='Added sugar in grams'),
        ),
    ]
